### PR TITLE
authentication improvements

### PR DESCRIPTION
**Pull request by Timi-Duban**
First version of #45 issue about new entry points to have new authentication features.
Please note that no emails are sent, they are logged for now.

Here's the password changing: we use the updateMutator to just change the user password and let the hooks of the user model handle the password security logic.

### CODE REVIEW

**Comment by eric-burel** [comment]
You mean we already have a hook for hashing the password? Password change should have a logic quite similar to signup, the main part being hashing the password correctly. In the signup form, I think we don't use Vulcan but instead directly passport.
Anyway, do whatever works, but please document in the PR how the password hashing will work because that's the critical part

**Comment by Timi-Duban** [comment]
About the changing password, we already have a callback inside the user model that trigger before the update, that uses the same password hashing than the creation hook. It's automatically called when we use the update mutator, so that's how I proceeded (no need to implement it in another way since it's already functional).

The signup form has the same logic: the password is just given to the create mutator without modifications, and the mutator triggers the callbacks inside the user model.

**Comment by Timi-Duban** [comment]
New commit: email verification !
Here we have an Input inside the User admin area that triggers the "email sending" (logged atm).
This leads to a new API entry point "sendVerificationEmail" that creates a token thanks to passport (iron to be precise).
After verifications, the goal was to send an Url to the user shaped like "basicUrl/verify-email/token", but as I said it's only logged atm.
This token is already OK, and there's a page at the corresponding route that uses passport/iron again to decrypt the token and confirm that it corresponds to an user email.

We still need to implement:
- the Url creation, since I didn't know how to access the basic app Url (I could have hardcoded "localhost" but I wanted it to be clear)
- The email sending
- The model logic: we can already know that someone followed the link but it has no effect on the model. 
I don't think it's wise to implement a systematic email verification to every new user since it's not always wanted by the developers... If you have any idea i'd be glad to implement something

**Comment by Timi-Duban** [comment]
New commit: forgotten password.
Here, you can access to the new page "forgottenPassword" from the login form.
This page uses the new API entry point "sendResetPasswordEmail", that creates a token containing the email in a similar way than "sendVerificationEmail".
Using this URL, the user will be able to be redirected to "/reset-password/[token]", which allows the user to put his new password and reset it by using the API entry point "changePassword", which is responsible from changing a user's password while connected (see the commit "change password") and now also resetting a password if we provide an email in the input.
So the entry point "changePassword" didn't change: it still uses the update mutator to modify the password field directly.

We still need to implement the Url creation and the email sending.

**Comment by eric-burel** [comment]
For the URL you should expect it to be set as a parameter, check how Meteor works for instance, it has a setting like this. You can have the same in Next like "NEXT_PUBLIC_FRONTEND_URL"

**Comment by Timi-Duban** [comment]
On Meteor we seem to use `Meteor.absoluteUrl()` that is mocked to "http://vulcanjs.org/" on the Git repo; I guess I would put "NEXT_PUBLIC_FRONTEND_URL" on both .env.development and .env.production, but I feel unsure about it so I'll let you take the final decision :)

**Comment by eric-burel** [comment]
@Timi-Duban Beware that `Meteor.absoluteUrl` might be client side only. So maybe the setting we have for this is from Vulcan Meteor and not Meteor. Server-side, you can never tell what the URL is, a server doesn't know its own domain (only its IP).

For Vulcan Next repo:
- in .env.development it should be something like `http://localhost:3000`
- in .env.production, it should be `https://vulcan-next.vercel.app`, that's where we deploy the demo version

Then user are expected to modify it in their .local files

**Comment by eric-burel** [comment]
I'll track the rest of the developments there: https://github.com/VulcanJS/vulcan-next/pull/124

Currently, your implementation does too much client-side or using getStaticPaths. Instead, the API route should do most of the security work, and the components should be quite simple, simply triggering calls to the relevant API. See `changePassword` for instance.

But that's a good working basis!

**Pull request closed without merging**
